version = 0.1
[default.deploy.parameters]
stack_name = "dig-indexer-sam"
resolve_s3 = true
s3_prefix = "dig-indexer-sam"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
